// Generated by scripts/gen-buildinfo.mjs. Do not edit by hand.

export const BUILD_INFO = {
  commit: "6ae6ed4+dirty",
  branch: "g3",
  buildTime: "2026-05-17T09:29:15.780Z",
  mode: "dev",
} as const;
