name: Build and Upload rpk

on:
  push:
    branches:
      - next-gen
  pull_request:
    branches:
      - next-gen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '20'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn

    - name: Build project
      run: npx aiot build --enable-custom-component --enable-jsc --enable-protobuf --enable-image-png8

    - name: Upload rpk files
      uses: actions/upload-artifact@v4.3.6
      with:
        name: RPK
        path: dist/**/*.rpk
