name: Build and Upload rpk

on:
  push:
    branches:
      - next-gen
  pull_request:
    branches:
      - next-gen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '20'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn

    - name: Build project (s3/s4)
      run: python scripts/build_s3s4.py

    - name: Upload rpk file (s3/s4)
      uses: actions/upload-artifact@v4.3.6
      with:
        name: RPK (Design Width 466) (For S3 S4)
        path: dist/**/*.rpk

    - name: Build project (rw5)
      run: python scripts/build_rw5.py

    - name: Upload rpk file (rw5)
      uses: actions/upload-artifact@v4.3.6
      with:
        name: RPK (Design Width 432) (RW5)
        path: dist/**/*.rpk